### ISSUE TITLE
Can't pickle swap object

### ISSUE THREAD

**Issue by cpadavis** [zooniverse/swap#4]
Hi there! Thanks for the work making swap a more friendly package!

I have a batch of test classifications in a local database. I am able to `run_swap swap --run` successfully and produce scores that seem reasonable. However, I cannot save the swap object to a pickle. Based on my understanding of the documentation, this also means I cannot run `run_swap scores` or `run_swap roc`. It looks like it has to do with the GoldGetter.

Any help is appreciated!

Here's the error I get:

```
> run_swap swap --run --save test.pkl --log test_pickle.log
/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/conf
/Users/cpd/.swaprc
20180410_11:03:15 INFO Initialized logging
20180410_11:03:17 INFO opening mongo connection
Database Handler initializing:
Host => localhost
DB => caesarTest
Port => 27017
20180410_11:03:17 INFO Processing gold labels
20180410_11:03:17 INFO Start: SWAP Processing 817 classifications
100% (817 of 817) |###################################################################| Elapsed Time: 0:00:00 Time:  0:00:0020180410_11:03:17 INFO done
20180410_11:03:17 INFO Generating history export
20180410_11:03:18 CRITICAL Can't pickle local object '_getter.<locals>.wrapper.<locals>.getter'
Traceback (most recent call last):
  File "/Users/cpd/anaconda3/bin/run_swap", line 11, in <module>
    load_entry_point('SWAP==1.0.4.dev8', 'console_scripts', 'run_swap')()
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/__main__.py", line 18, in main
    raise e
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/__main__.py", line 15, in main
    ui.run()
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/__init__.py", line 59, in run
    ui.run()
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/ui.py", line 37, in run
    self.call(args)
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/ui.py", line 121, in call
    args.func(args)
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/swap.py", line 202, in call
    self.save(swap, self.f(args.save[0]), manifest)
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/swap.py", line 389, in save
    super().save(obj, fname)
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/ui.py", line 229, in save
    save_pickle(obj, fname)
  File "/Users/cpd/anaconda3/lib/python3.6/site-packages/SWAP-1.0.4.dev8-py3.6.egg/swap/ui/utils.py", line 28, in save_pickle
    pickle.dump(object_, file)
AttributeError: Can't pickle local object '_getter.<locals>.wrapper.<locals>.getter'
20180410_11:03:18 INFO closing mongo connection
- |#                                                                                               | 0 Elapsed Time: 0:00:00%
```

I get a similar error passing the --save-scores flag.

Here is the output from the log file in the swap directory (It appears a log file was not produced at my specified location?)
```
20180410_11:12:04:INFO::root:init Initialized logging
20180410_11:12:08:DEBUG::swap.ui.ui:run Namespace(back=False, config_file=None, consensus=None, controversial=None, db=None, diff=None, dir=None, dist=None, export_user_scores=None, func=<bound method SWAPInterface.call of <swap.ui.swap.SWAPInterface object at 0x116dfc208>>, hist=None, load=None, log=['test_pickle.log'], multiply=False, noback=False, p0=None, pow=False, presrec=None, run=True, save=['test.pkl'], save_scores=None, scores_from_csv=None, scores_to_csv=None, shell=False, stats=False, subject=None, test=False, test_reorder=False, train=None, user=None)
20180410_11:12:08:INFO::swap.db:__init__ opening mongo connection
20180410_11:12:08:DEBUG::swap.control:init_swap Initializing SWAP
20180410_11:12:08:DEBUG::swap.utils.golds:wrapper Using getter <function GoldGetter.all at 0x10d106598>
20180410_11:12:08:INFO::swap.swap:set_gold_labels Processing gold labels
20180410_11:12:08:DEBUG::swap.db.db:aggregate Preparing to run aggregation
20180410_11:12:08:DEBUG::swap.db.db:aggregate collection classifications query [{'$match': {'seen_before': False}}, {'$sort': {'classification_id': 1}}, {'$project': {'user_id': 1, 'subject_id': 1, 'annotation': 1, 'session_id': 1}}] args {'batchSize': 100000}
20180410_11:12:08:DEBUG::swap.db.db:__init__ Cursor query: [{'$match': {'seen_before': False}}, {'$sort': {'classification_id': 1}}, {'$project': {'user_id': 1, 'subject_id': 1, 'annotation': 1, 'session_id': 1}}]
20180410_11:12:08:INFO::swap.control:run Start: SWAP Processing 817 classifications
20180410_11:12:08:INFO::swap.control:run done
20180410_11:12:08:INFO::swap.swap:history_export Generating history export
20180410_11:12:08:DEBUG::swap.swap:history_export done
20180410_11:12:08:DEBUG::swap.utils.golds:wrapper Using getter <function GoldGetter.all at 0x10d106598>
20180410_11:12:08:DEBUG::swap.utils.scores:find_thresholds determining retirement thresholds fpr 0.010 mdr 0.100
20180410_11:12:08:DEBUG::swap.utils.scores:find_thresholds bogus 0.0692 real 0.2242, fpr 0.0000 mdr 0.1000
20180410_11:12:08:DEBUG::swap.utils.scores:get_real_golds Getting real gold labels from db
20180410_11:12:08:CRITICAL::swap:main Can't pickle local object '_getter.<locals>.wrapper.<locals>.getter'
20180410_11:12:08:INFO::swap.db:close closing mongo connection
```

**Comment by miclaraia** [comment]
Marking as closed for now, let me know if there is a similar problem with swap-2
